# .travis.yml
language: php

php:
  - '5.6'

before_script:
  - composer install --dev --no-interaction
  - php artisan key:generate

script:
  - php artisan
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v