language: php
php:
- '5.6'
before_script:
- cp .env.travis .env
- mysql -e 'create database actmon_test;'
- composer install --dev --no-interaction
- php artisan key:generate
script:
- mkdir -p build/logs
- chmod -R 777 build/logs
#- vendor/bin/phpunit tests
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls -v
notifications:
  email: false
  slack:
    secure: u3Cu7IssmW1R3QDq373H+PzYWzEZY1OL/vq5lI+bFMG2fZToaOtSzzIHP9T4MFFDM99v8NSaWLh4QfuBI4WCkRq8g/QcDAI9g03Xgm9ylAPS6IUysVTKTBn0hoNSSSReXUaHP3bxx44iwhikOK9ExBiPaFJtYvihcQM7A1YihtTfyT31+G8aW2QgFWda4lGfIsQqbgTKT8AyCrgJ4+VqSHuav/sMD3tbwEDELyIVg6jOCraUSXdnuyYEF7df0FZLiUl60kegkrKi5fSCOyemqj6DMs2F4xHuZbOMNwpIlFtMruubm52gbMQu4R7J96oEuCoT+F7vBs8ZUECdAIuDXYLkCsrUNlDyRkyPkGmKacBg92UGDzyZwtFqPKNe8Xm6rFAJhT95qR+QsxyMziVqgI3RBPFAmR4IwII4OnKJkuZbkjPyP7N5tyr5U6zY+yGDGBuEv+lXcLOnC58+jQTe1q3HRYYXVjya826oKUTOqdSjGyvmlOqVTKTU5oxnM+nombBCCN0AQPMDUCMt8hECN6DEdT+QnlENU0sa5sZMCIrcASx19H2nVglrgJ11y3Nih10MeK9QCBfC96EpxY9TIcnJA5+N+OUnGFlVHRe0Y916yJjKK0+GdAhaKWKBKBc7XOXXseHTT+zPVJXvNavrOShcccgCUVTqchKmH/PFvEM=
deploy:
  provider: heroku
  api_key:
    secure: dfvgBwAs6OobQ/c7AhxQ2MtuGk7ZeF2v2qgVGTDBrtiWgXXWiqiokfkYSJMiwOC0aCyZLMv2suKiz50+TGQvYknV85+mcgz2eSy9nVzp1lckoFFPrVSfcYKmMaqxIxpSXq91T3dq4WilIk8jsFgT2FC0fRhIoySEfa5UbBDMWU6oDwJJkUTOiR0if5Q0Fi6K3mcWCHATBtaOv2lV4B3rdq6xZ3ilw47X/BZPQCf/9j8zNXX70gN+5yYgLkji1U6L1M6oKXGuC/t+LqhBIccKYL+dhMjes2uxdHBkznsuW/Y8EmCXXhISNpMGB6YkA/kSRn4Ue3vUbh1v8sZOuNekio8MPz188l3U61aCf30bpQu3U1sBekYAP6eNv8k0/UWwCE0oNOdJ7mftDqmBbM5CzvbSWqTtuuXXMTk3xAEO+zJYBEPt9suOXn2w+0PHf46J54nZ1fZ9/jz0W98Q8lgh5hHI0t2BHnecLhRn7zNPHbEmxdaXHHruN/MVBqE7ckGXrRoSBf1y4ZC/zIIxm6b6Evf3kEdqqvtDNUKTRefIsOIZ4+15SWgQX4r9aeoSVX/MLBF60zhrhp+gvQ6XFgxbtO0t4JUNYrxdrc5g78HpzCkHULVk5Q8E34OOI2EYxgFbaov1vT6oUZWnHDtGsE+rzRaipm7NzBSWywmVgScdpm8=
  app: cryptic-lake-66504
  on:
    repo: gozaing/actmon
